#!/bin/bash

threshold=10

while true
do
  battery_level=$(acpi -b | grep -P -o '[0-9]+(?=%)')
    if [ "$battery_level" -le $threshold ]; then
      notify-send --urgency=CRITICAL "Battery Low" "Level: ${battery_level}%"
  fi
 sleep 60
done
