#!/bin/bash

# finder_cmd="rofi -dmenu -p config"
finder_cmd="fzf"

config_paths=(
  "fish/config.fish"
  "nvim/lua/user/"
  "qtile/"
  "ranger/"
  "rofi/"
  "picom/"
  "alacritty/alacritty.yml"
)

home_paths=(
  ".bashrc"
  ".xinitrc"
)

etc_paths=(
  "X11/xorg.conf.d/"
)


file_list=$(printf '%s\n' "${home_paths[@]}" "${etc_paths[@]}" "${config_paths[@]}" | rg "$1")

file_amount=$(echo "$file_list" | wc -l)

if [ "$file_amount" == 1 ]; then
  selected_file="$file_list"
else
  selected_file=$(echo "$file_list" | "$finder_cmd")
fi


if printf '%s\n' "${home_paths[@]}" | grep -q "^$selected_file$"; then
  selected_file="$HOME/$selected_file"
elif printf '%s\n' "${etc_paths[@]}" | grep -q "^$selected_file$"; then
  selected_file="/etc/$selected_file"
elif printf '%s\n' "${config_paths[@]}" | grep -q "^$selected_file$"; then
  selected_file="$HOME/.config/$selected_file"
fi

"$EDITOR" "$selected_file"
