#!/bin/env node
const { spawn } = require("child_process");
const fs = require("fs");

const d = new Date();

const offset = parseInt(process.argv[2] ?? 0);

d.setDate(d.getDate() + offset);

let day = d.getDate().toString();
if (day.length == 1) day = `0${day}`;

let month = (d.getMonth() + 1).toString();
if (month.length == 1) month = `0${month}`;

const year = d.getFullYear();

const date = `${day}-${month}-${year}`;

const basePath = `/home/${process.env.USER}/notes`;

if (!fs.existsSync(`${basePath}/#7 dailyNotes/${date}.md`)) {
  fs.copyFile(
    `${basePath}/#6 _templates/dailyNoteTemplate.md`,
    `${basePath}/#7 dailyNotes/${date}.md`,
    () => { }
  );
}

spawn(process.env.EDITOR ?? "nvim", [`${basePath}/#7 dailyNotes/${date}.md`], {
  stdio: "inherit",
});
