#!/bin/env node
const { spawn } = require("child_process");
const fs = require("fs");

const d = new Date();

const offset = parseInt(process.argv[2] ?? 0);

d.setDate(d.getDate() + offset);

let day = d.getDate().toString();
if (day.length == 1) day = `0${day}`;

let month = (d.getMonth() + 1).toString();
if (month.length == 1) month = `0${month}`;

const year = d.getFullYear();
const weekday = d.toLocaleDateString("en-US", { weekday: "long" });

const date = `${day}-${month}-${year}`;
const dateWithWeekday = `${date} ${weekday}`;

const basePath = `/home/${process.env.USER}/notes`;
const source = `${basePath}/#6 _templates/dailyNoteTemplate.md`;
const destination = `${basePath}/#7 dailyNotes/${date}.md`;

if (!fs.existsSync(destination)) {
  fs.readFile(source, "utf-8", function(err, data) {
    if (err) throw err;

    const changedVarsContent = data.replace(/{date}/gim, dateWithWeekday);

    fs.writeFileSync("/tmp/dailyNote", changedVarsContent);

    fs.copyFileSync("/tmp/dailyNote", destination);
  });
}

spawn(process.env.EDITOR ?? "nvim", [destination], {
  stdio: "inherit",
});
