#!/bin/bash

finder_cmd="fzf"

notes_path="$HOME/notes/"

file_list=$(printf '%s\n' "$(find "$notes_path" -type d )"  | rg -i "$1")

file_amount=$(echo "$file_list" | wc -l)

if [ "$file_amount" == 1 ] && [ "$file_list" != "" ]; then
  selected_file="$file_list"
elif [ "$file_list" == "" ]; then
  selected_file=$(ls "$notes_path" | "$finder_cmd")
else
  selected_file=$(echo "$file_list" | "$finder_cmd")
fi

if [ "$selected_file" == "" ]; then
  exit 0
fi

"$EDITOR" "$selected_file"
