#!/bin/bash

glyphs=$(curl -s https://raw.githubusercontent.com/groovykiwi/rofi-nerdfont/master/nerd-font-cheatsheet.txt)

menu_cmd="rofi -dmenu -p 'NF Cheatsheet' -columns 2 -width 40"

selected=$(echo "$glyphs" | eval "$menu_cmd")

selected=$(
  echo "$selected" |
  cut -d" " -f2 |
  tr '\n' ' ' |
  sed 's/⠀//g; s/\s//g' 

)

echo "$selected" | xclip -selection clipboard
