#!/usr/bin/env bash

glyphs=$(curl -s https://raw.githubusercontent.com/groovykiwi/rofi-nerdfont/master/nerd-font-cheatsheet.txt)

menu_cmd="rofi -dmenu -p 'NF Cheatsheet' -columns 2 -width 40"

selected=$(echo "$glyphs" | eval "$menu_cmd")

# Remove first column, all spaces, and join into a single line
selected=$(echo "$selected" | awk '{print $1}' | tr -d '[:space:]')

echo -n "$selected" | xclip -selection clipboard
