#!/bin/env node
const { spawn } = require("child_process");
const { readFile } = require("fs/promises");

(async () => {
  const num = await getFileNum();

  spawnNvim(getFilePath(num));
})();

function getFilePath(n = 0) {
  const basePath = "/tmp/";
  const baseFilename = "tmp_";
  const ext = process.argv[2] ?? "md";
  const fullFilename = `${baseFilename}${n}.${ext}`;
  const fullPath = `${basePath}${fullFilename}`;

  return fullPath;
}

async function getFileNum(n = 0) {
  try {
    await readFile(getFilePath(n));
    return await getFileNum(n + 1);
  } catch (_err) {
    return n;
  }
}

function spawnNvim(path) {
  spawn(process.env.EDITOR ?? "nvim", [path], {
    stdio: "inherit",
  });
}
